### ISSUE TITLE
Change audio instruments

### ISSUE THREAD

**Issue by piteight** [googlecreativelab/aiexperiments-ai-duet#13]
Hi there, I have succesfully installed and used Your code, but I want to change some things a little.
I have changed mp3 files in static/audio/Salamander to my guitar samples, but when I did that, the page stuck on loading - nothing happens.
I'm looking forward for your response :D

**Comment by tambien** [comment]
Make sure the file names are exactly the same as the ones that you're replacing. It should include C, D#, F# and A in the octaves 0-7. But notice that for D# and F#, the '#' is replaced with an 's' because the '#' symbol causes problems with some servers. e.g. D#2.mp3 should be named Ds2.mp3

Hope that helps

**Comment by piteight** [comment]
Hi there! Thank You for reply, your answer was helpful, but there is one more thing that I've done to get it working - mp3 files must be stereo tracks, just like original ones. When mp3 is mono channel, ai duet wont load it.
